// <auto-generated />
using Azure.SQLDB.Samples.DynamicSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Azure.SQLDB.Samples.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20250730174735_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("global_sequence");

            modelBuilder.Entity("Azure.SQLDB.Samples.DynamicSchema.ToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next value for dbo.global_sequence")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<byte>("Completed")
                        .HasColumnType("tinyint")
                        .HasColumnName("completed")
                        .HasAnnotation("Relational:JsonPropertyName", "completed");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("todo")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.HasKey("Id");

                    b.ToTable("todo_hybrid");
                });

            modelBuilder.Entity("Azure.SQLDB.Samples.DynamicSchema.ToDo", b =>
                {
                    b.OwnsOne("Azure.SQLDB.Samples.DynamicSchema.ToDoExtension", "Extensions", b1 =>
                        {
                            b1.Property<int>("ToDoId")
                                .HasColumnType("int");

                            b1.Property<int>("Order")
                                .HasColumnType("int")
                                .HasAnnotation("Relational:JsonPropertyName", "order");

                            b1.HasKey("ToDoId");

                            b1.ToTable("todo_hybrid");

                            b1
                                .ToJson("extension")
                                .HasColumnType("json");

                            b1.WithOwner()
                                .HasForeignKey("ToDoId");
                        });

                    b.Navigation("Extensions");
                });
#pragma warning restore 612, 618
        }
    }
}
